---
- debug:
    msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"
- debug:
    msg: "{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
- debug:
    msg: "{{ hostvars[inventory_hostname].ansible_distribution_version }}"

# - name: "Add Debian openvas"
#   include_tasks: openvas_debian.yml
#   when: " ansible_os_family == 'Debian' and ansible_distribution in ['Debian','Ubuntu'] "

# - name: "Add RedHat openvas"
#   include_tasks: openvas_redhat.yml
#   when: " ansible_os_family == 'RedHat' and ansible_distribution in ['CentOS','Scientific'] "

# - name: "preinstall task"
#   include_tasks: pre_install.yml